#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export PYTHONPATH="${ROOT}:${ROOT}/finetune"
export KMP_DUPLICATE_LIB_OK="TRUE"
export KRONOS_DATASET_PATH="${KRONOS_DATASET_PATH:-${ROOT}/data/a_share_v3/processed_datasets}"
export KRONOS_METADATA_PATH="${KRONOS_METADATA_PATH:-${ROOT}/data/a_share_v3/asset_metadata.csv}"
export KRONOS_PREDICTOR_PATH="${KRONOS_PREDICTOR_PATH:-${ROOT}/outputs/models/a_share_size_full_coverage_colab_bs32_latest/checkpoints/best_model}"
export KRONOS_SAVE_PATH="${KRONOS_SAVE_PATH:-${ROOT}/outputs/models}"
export KRONOS_PREDICTOR_SAVE_FOLDER="${KRONOS_PREDICTOR_SAVE_FOLDER:-a_share_size_full_market_v3}"
export KRONOS_RESET_SIZE_EMBEDDING="${KRONOS_RESET_SIZE_EMBEDDING:-1}"
export KRONOS_BALANCE_SIZE_BUCKETS="${KRONOS_BALANCE_SIZE_BUCKETS:-1}"
export KRONOS_USE_SIZE_PERCENTILE="${KRONOS_USE_SIZE_PERCENTILE:-0}"
export KRONOS_TRAIN_SAMPLES_PER_SEGMENT="${KRONOS_TRAIN_SAMPLES_PER_SEGMENT:-20000}"
export KRONOS_VALIDATION_SAMPLES="${KRONOS_VALIDATION_SAMPLES:-4000}"
export KRONOS_COVERAGE_PASSES="${KRONOS_COVERAGE_PASSES:-1}"
export KRONOS_REQUIRE_FULL_COVERAGE="${KRONOS_REQUIRE_FULL_COVERAGE:-1}"
export KRONOS_EARLY_STOPPING_PATIENCE="${KRONOS_EARLY_STOPPING_PATIENCE:-5}"
export KRONOS_BATCH_SIZE="${KRONOS_BATCH_SIZE:-32}"
export KRONOS_NUM_WORKERS="${KRONOS_NUM_WORKERS:-2}"

cd "${ROOT}"
exec python -u finetune/train_predictor.py
